const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  USER: 'user',
};

const TOKEN_TYPES = {
  ACCESS: 'access',
  REFRESH: 'refresh',
};

const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ACCESS: 'ACCESS',
};

const ERROR_CODES = {
  VALIDATION_ERROR: 1001,
  AUTHENTICATION_ERROR: 1002,
  AUTHORIZATION_ERROR: 1003,
  NOT_FOUND_ERROR: 1004,
  CONFLICT_ERROR: 1005,
  RATE_LIMIT_ERROR: 1006,
  IP_BLOCKED_ERROR: 1007,
  INTERNAL_ERROR: 1008,
};

const REDIS_KEYS = {
  IP_BLOCK: 'ip_block',
  RATE_LIMIT: 'rate_limit',
  FAILED_LOGIN: 'failed_login',
  TOKEN_BLACKLIST: 'token_blacklist',
};

const LIMITS = {
  MAX_FAILED_LOGINS: 5,
  IP_BLOCK_TTL: 3600,
  RATE_LIMIT_WINDOW: 900,
  RATE_LIMIT_MAX: 100,
  BODY_SIZE: '10mb',
};

module.exports = { HTTP_STATUS, ROLES, TOKEN_TYPES, AUDIT_ACTIONS, ERROR_CODES, REDIS_KEYS, LIMITS };
